// Internal NestJS EventEmitter event names from CLAUDE.md Section 3.
// Transport-level events (for example Socket.io `domain:action`) are defined separately.

export const DOMAIN_EVENTS = {
  ORDER: {
    CREATED: 'order.created',
    STATUS_CHANGED: 'order.status-changed',
  },
  ROUTE: {
    BUILT: 'route.built',
    CANCELLED: 'route.cancelled',
    UPDATED: 'route.updated',
  },
  PAYMENT: {
    APPROVED: 'payment.approved',
    CALCULATED: 'payment.calculated',
    DISPUTED: 'payment.disputed',
  },
  SHIFT: {
    CONFIRMED: 'shift.confirmed',
    STARTED: 'shift.started',
  },
  COURIER: {
    LOCATION_UPDATED: 'courier.location-updated',
  },
  INTEGRATION: {
    WEBHOOK_FAILED: 'integration.webhook-failed',
  },
} as const;

export const DOMAIN_EVENT_NAMES = {
  ORDER_CREATED: DOMAIN_EVENTS.ORDER.CREATED,
  ORDER_STATUS_CHANGED: DOMAIN_EVENTS.ORDER.STATUS_CHANGED,
  ROUTE_BUILT: DOMAIN_EVENTS.ROUTE.BUILT,
  ROUTE_CANCELLED: DOMAIN_EVENTS.ROUTE.CANCELLED,
  ROUTE_UPDATED: DOMAIN_EVENTS.ROUTE.UPDATED,
  PAYMENT_APPROVED: DOMAIN_EVENTS.PAYMENT.APPROVED,
  PAYMENT_CALCULATED: DOMAIN_EVENTS.PAYMENT.CALCULATED,
  PAYMENT_DISPUTED: DOMAIN_EVENTS.PAYMENT.DISPUTED,
  SHIFT_CONFIRMED: DOMAIN_EVENTS.SHIFT.CONFIRMED,
  SHIFT_STARTED: DOMAIN_EVENTS.SHIFT.STARTED,
  COURIER_LOCATION_UPDATED: DOMAIN_EVENTS.COURIER.LOCATION_UPDATED,
  INTEGRATION_WEBHOOK_FAILED: DOMAIN_EVENTS.INTEGRATION.WEBHOOK_FAILED,
} as const;

export const ALL_DOMAIN_EVENT_NAMES = [
  DOMAIN_EVENT_NAMES.ORDER_CREATED,
  DOMAIN_EVENT_NAMES.ORDER_STATUS_CHANGED,
  DOMAIN_EVENT_NAMES.ROUTE_UPDATED,
  DOMAIN_EVENT_NAMES.ROUTE_BUILT,
  DOMAIN_EVENT_NAMES.ROUTE_CANCELLED,
  DOMAIN_EVENT_NAMES.PAYMENT_CALCULATED,
  DOMAIN_EVENT_NAMES.PAYMENT_APPROVED,
  DOMAIN_EVENT_NAMES.PAYMENT_DISPUTED,
  DOMAIN_EVENT_NAMES.SHIFT_CONFIRMED,
  DOMAIN_EVENT_NAMES.SHIFT_STARTED,
  DOMAIN_EVENT_NAMES.COURIER_LOCATION_UPDATED,
  DOMAIN_EVENT_NAMES.INTEGRATION_WEBHOOK_FAILED,
] as const;

export type DomainEventName = (typeof ALL_DOMAIN_EVENT_NAMES)[number];

const DOMAIN_EVENT_NAME_SET: ReadonlySet<string> = new Set(
  ALL_DOMAIN_EVENT_NAMES,
);

export function isDomainEventName(value: string): value is DomainEventName {
  return DOMAIN_EVENT_NAME_SET.has(value);
}
